// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cznsxhpqwnrjuebxjvrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bnN4aHBxd25yanVlYnhqdnJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTg5NjYsImV4cCI6MjA2OTEzNDk2Nn0.ztbd7kL9XHrWPY4Mz9CpPlbMVD3vIUSH1iziD0kUyeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});